export const interestPoints = [
  {
    id: 1,
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/Casa_de_la_Cultura_Ecuatoriana_01.JPG/1200px-Casa_de_la_Cultura_Ecuatoriana_01.JPG",
    name: "Casa de la Cultura",
    value: "Casa de la Cultura de la Ciudad de México",
    lat: 19.4326,
    lng: -99.1332,
    description: "Casa de la Cultura de la Ciudad de México",
    category: "Cultural",
  },
  {
    id: 2,
    img: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Museo_de_la_Ciudad_de_M%C3%A9xico._Fotograf%C3%ADa_Viviana_Mart%C3%ADnez_2017.jpg",
    name: "Museo de la Ciudad de México",
    value: "Museo de la Ciudad de México",
    lat: 19.4326,
    lng: -99.1332,
    description: "Museo de la Ciudad de México",
    category: "Cultural",
  },
  {
    id: 3,
    img: "https://www.mexicoescultura.com/galerias/espacios/principal/museo_arte_popular_2.jpg",
    name: "Museo de Arte Popular",
    value: "Museo de Arte Popular",
    lat: 19.4326,
    lng: -99.1332,
    description: "Museo de Arte Popular",
    category: "Cultural",
  },
  {
    id: 4,
    img: "https://www.restauranteelcardenal.com/images/00.jpg?crc=3765039244",
    name: "Restaurante 'El Cardenal'",
    value: "Restaurante 'El Cardenal'",
    lat: 19.4326,
    lng: -99.1332,
    description: "Restaurante 'El Cardenal'",
    category: "Gastronomy",
  },
  {
    id: 5,
    img: "https://www.laguiacdmx.com/wp-content/uploads/2022/12/cafe-de-tacuva-1.jpg",
    name: "Café de Tacuba",
    value: "Café de Tacuba",
    lat: 19.4326,
    lng: -99.1332,
    description: "Café de Tacuba",
    category: "Gastronomy",
  },
  {
    id: 6,
    img: "https://cdn.onefc.com/wp-content/uploads/2020/03/Christian-Lee-Ken-Lee-Angela-Lee-United-MMA-1200X800.jpg",
    name: "MMA Gym 'La Roca'",
    value: "MMA Gym 'La Roca'",
    lat: 19.4326,
    lng: -99.1332,
    description: "MMA Gym 'La Roca'",
    category: "Sports",
  },
];
